In [1]:
import pandas as pd
import numpy as np
from openff.toolkit.topology import Molecule
from openff.units import unit


In [2]:
df = pd.read_parquet('/mnt/storage/nobackup/nca121/paper_charge_comparisons/async_chargecraft_more_workers/charge_models.parquet')
df

mbis_charges  \
0   [-0.44171691769759425, 0.19215883543444148, -0...   
1   [-0.273265076200354, 0.19154401299583018, -0.4...   
2   [-0.2802437287551881, 0.19371228800835663, -0....   
3   [-0.37792107365792155, 0.20088590130080047, -0...   
4   [-0.20271783777574814, 0.11143350543999422, -0...   
5   [0.18318003045342993, -0.2598634431943842, -0....   
6   [-0.3450779454676982, 0.20008738362730868, -0....   
7   [-0.3156871232247241, 0.18534362796853993, -0....   
8   [-0.3125480447902324, 0.1942019294195022, -0.4...   
9   [-0.307478181466797, -0.32475236546718506, 0.0...   
10  [-0.2574581571300071, 0.18259062892452851, -0....   
11  [-0.3428219539005908, -0.08263195293754468, -0...   
12  [-0.25438345864210027, 0.17302388158357446, -0...   
13  [-0.26623933328724575, 0.18200228402093238, -0...   
14  [-0.2644418223209909, 0.1874607181407954, -0.4...   
15  [-0.2533565313304609, 0.17527590433684306, -0....   
16  [-0.22269026300546416, 0.0986548857271199, -0....   
17  [-0.3620213270833899, 0.20638835550511864, -0....   
18  [-0.4380052176132638, 0.31733133575155187, -0....   
19  [-0.45022252463765217, 0.34007067007117325, -0...   
20  [-0.21084113825290324, 0.11286933447655992, -0...   
21  [-0.1757893460381756, -0.1637683300983637, -0....   
22  [-0.48990797728740026, 0.6509841207487627, -0....   
23  [-0.4729401284291233, 0.6551711305221624, -0.5...   
24  [-0.49153674348150345, 0.6525708780987155, -0....   
25  [-0.47475551802153954, 0.6582049130983133, -0....   
26  [-0.4731195959540249, 0.6551371714072554, -0.5...   
27  [-0.2793171712340214, -0.21314216495858515, 0....   
28  [-0.2481155542824418, -0.2583646041198432, 0.2...   
29  [-0.25333875570048014, -0.2648906556505997, 0....   
30  [-0.24965667889410528, -0.25109157997425496, 0...   
31  [-0.27024134000385275, -0.2514930826279807, 0....   
32  [-0.25576208790277083, -0.2525614470001997, 0....   
33  [-0.15125741593148082, -0.27358930891295247, 0...   
34  [-0.19319478653545497, -0.20507698526640464, 0...   
35  [-0.2749579343570758, 0.10869784862803485, -0....   
36  [-0.06495081158928515, -0.5266801610625936, 1....   
37  [-0.33786205482858656, -0.11023125829540968, -...   
38  [-0.3423109844909345, -0.09889443288913055, -0...   
39  [-0.3409960602937301, -0.09854868710135062, -0...   
40  [-0.3415899889759827, -0.10131981289447732, -0...   
41  [-0.3423141343534261, -0.09880364611926472, -0...   
42  [-0.42486960676507085, 0.22035419736205136, -0...   
43  [-0.3916727282109761, -0.1399690807348578, -0....   
44  [-0.6820838345853792, 1.8501020275655893, -0.7...   
45  [-0.6818958034974583, 1.8494490536748247, -0.7...   
46  [-0.06668376647639025, -0.45541952844800415, 0...   
47  [-0.6820049071569746, 1.8498335813782851, -0.7...   
48  [-0.6820231057590653, 1.849893204814243, -0.78...   
49  [-0.6819722404016412, 1.8497288973231634, -0.7...   
50  [-0.22978003231558222, 0.11802921002756239, -0...   
51  [-0.39858286076805627, 0.2432112952197822, -0....   
52  [-0.059940642806782074, -0.44598290270380053, ...   

                                       am1bcc_charges  \
0   [-0.15928235294117646, 0.13051764705882352, -0...   
1   [-0.1094, 0.1304, -0.4296, 0.1141, -0.00559999...   
2   [-0.1094, 0.1304, -0.4296, 0.1141, -0.00559999...   
3   [-0.14128235294117647, 0.12751764705882354, -0...   
4   [-0.0914, 0.1428, -0.7922, 0.1578, -0.138, 0.1...   
5   [0.1214, -0.0273, -0.3572, 0.1952, -0.3976, 0....   
6   [-0.12334444444444444, 0.12345555555555555, -0...   
7   [-0.12334444444444444, 0.12345555555555555, -0...   
8   [-0.12334444444444444, 0.12345555555555555, -0...   
9   [-0.1269, -0.1269, -0.111, -0.0814, 0.1528, -0...   
10  [-0.10544761904761903, 0.12935238095238097, -0...   
11  [-0.09104995, -0.07964995, -0.10834995, 0.1274...   
12  [-0.10544761904761903, 0.12935238095238097, -0...   
13  [-0.10544761904761903, 0.12935238095238097, -0...   
14  [-0.10544761904761903, 0.12935238095238097, -0...   
15  [-0.10544761904761903, 0.12935238095238097, -0

In [3]:
df.to_csv('./sanity_check.csv')

In [4]:
df.iloc[0]

mbis_charges                [-0.44171691769759425, 0.19215883543444148, -0...
am1bcc_charges              [-0.15928235294117646, 0.13051764705882352, -0...
espaloma_charges            [-0.2646322256940253, 0.09048017793718506, -0....
riniker_monopole_charges                                                 None
resp_charges                [-0.2238, 0.1144, -0.3794, 0.1839, 0.4749, -0....
qm_dipoles                                                           0.372726
mbis_dipoles                                                         0.196034
am1bcc_dipole                                                        0.099876
espaloma_dipole                                                      0.568253
riniker_dipoles                                                      0.042476
resp_dipole                                                          0.179598
molecule                    [H][O][C]([H])([H])[C]1([H])[O][C]([H])([H])[C...
grid                        [[-4.959543008824821, -1.43442623955

In [5]:
from chargecraft.storage.storage import MoleculePropRecord, MoleculePropStore
from MultipoleNet import load_model, build_graph_batched, D_Q
riniker_model = load_model()


2024-11-15 15:46:38.691821: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead


In [6]:
prop_store = MoleculePropStore('/mnt/storage/nobackup/nca121/paper_charge_comparisons/async_chargecraft_more_workers/ESP_rebuilt.db')
prop_store.list()

['OCC1OCCS1',
 'OCC1OCCC1F',
 'OCC1OCCC1S',
 'O=NC1CCOC1CO',
 'OCC1OCCC1(F)F',
 'C1CC2(CN1)COC2',
 'O=[N+]([O-])C1CCOC1CO',
 'NC1CCOC1CO',
 '[N-]=[N+]=NC1CCOC1CO',
 'CC1CCOC1CO',
 'OCC1CCOC1CO',
 'C1CC2(CCN1)CC2',
 'CC1(O)CCOC1CO',
 'FC1(F)CC12CCNCC2',
 '[NH3+]C1(O)CCOC1CO',
 'CC(=O)SC1CCOC1CO',
 'NC1CC12CCNCC2',
 'C1CCC2(C1)CCNC2',
 'C[NH+](C)C1CCOC1CO',
 'CP(=O)([O-])OC1CCOC1CO',
 'OCC1CCCCO1',
 'OCC1OCCCC1O',
 'OCC1CCCO1',
 '[NH3+]CCSSC1CCOC1CO',
 'CSSC1CCOC1CO',
 '[N-]=[N+]=NCC1CCOC1CO',
 'C1CC2(CC[NH2+]CC2)CN1',
 'C1CC2(CCN1)CCNC2',
 'C1CC2(CCN1)C1C[NH2+]CC12',
 'C1CC2(C1)CCNC2',
 'CN1C(=O)NCC12CCNCC2',
 'O=C1CCC2(CCNCC2)CN1',
 'CCOC1CC2(CCNC2)C1',
 '[NH3+]C1CCOC1CO',
 'CS(=O)(=O)OC1CCOC1CO',
 'CN1CCC2(CCNC2)CC1',
 'CN1CCOCC12CCNCC2',
 'CC1CC2(CCNCC2)CN1',
 'C[NH+]1CCOCC12CCNCC2',
 'C1CC2(CCNC2)CN1',
 'C=C1CCOC1CO',
 'OCC1CNCCO1',
 'C1CC2(CN1)CNC2',
 'OCC1OCCC(O)C1O',
 'C1CC2(CCN1)COC2',
 'N#CSC1CCOC1CO',
 'OCC1OCCC1O',
 'NC1(O)CCOC1CO',
 'C[NH+]1CC2(CCNC2)C1',
 'NCC1CC12CCNCC2',


In [ ]:
molecule = prop_store.retrieve(smiles='OCC1OCCS1')

In [ ]:
mapped_smiles = molecule[0].tagged_smiles
conformer_quantity = molecule[0].conformer_quantity
openff_mol = Molecule.from_mapped_smiles(mapped_smiles=mapped_smiles, allow_undefined_stereo=True)
openff_mol.add_conformer(conformer_quantity)
rdkit_conformer = openff_mol.to_rdkit()
elements = [a.GetSymbol() for a in rdkit_conformer.GetAtoms()]
coordinates = rdkit_conformer.GetConformer(0).GetPositions().astype(np.float32)

In [ ]:
from espaloma_charge.openff_wrapper import EspalomaChargeToolkitWrapper

toolkit_wrapper = EspalomaChargeToolkitWrapper()

openff_mol.assign_partial_charges('espaloma-am1bcc', toolkit_registry=toolkit_wrapper)

/mnt/nfs/home/nca121/mambaforge/envs/charge_model_env/lib/python3.11/site-packages/espaloma_charge/openff_wrapper.py:112: IncorrectNumConformersWarning: Molecule 'Molecule with name '' and SMILES '[H][O][C]([H])([H])[C]1([H])[O][C]([H])([H])[C]([H])([H])[S]1'' has 1 conformers, but charge method 'espaloma-am1bcc' expects exactly 0.
  self._check_n_conformers(
/mnt/nfs/home/nca121/mambaforge/envs/charge_model_env/lib/python3.11/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(


In [ ]:
openff_mol.partial_charges

array([ 0.10370073, -0.20816672, -0.29328483,  0.09934076, -0.37793287,
        0.18753447, -0.68438011,  0.1105975 ,  0.1105975 ,  0.14053039,
        0.14053039,  0.11685429,  0.08291832,  0.08291832,  0.38824186]) <Unit('elementary_charge')>

In [ ]:
molecule[0].mbis_charges_quantity

array([[ 0.18318003],
       [-0.25986344],
       [-0.23324592],
       [ 0.20927146],
       [-0.43504134],
       [ 0.13056606],
       [-0.66881527],
       [ 0.07737889],
       [ 0.05457898],
       [ 0.13401891],
       [ 0.14239135],
       [ 0.08841999],
       [ 0.06529237],
       [ 0.05497736],
       [ 0.4569254 ]]) <Unit('elementary_charge')>

In [ ]:
test_mol = prop_store.retrieve(smiles='[H][O][C]([H])([H])[C]1([H])[O][C]([H])([H])[C]([H])([H])[C]1([F])[F]')

In [ ]:
test_mol[0].mbis_charges_quantity

array([[-0.44171692],
       [ 0.19215884],
       [-0.43095924],
       [ 0.03781578],
       [ 0.69789878],
       [-0.30650265],
       [-0.31078307],
       [ 0.15108314],
       [-0.68119875],
       [ 0.15312256],
       [ 0.15044178],
       [ 0.07560967],
       [ 0.04216704],
       [ 0.09957404],
       [ 0.06347353],
       [ 0.0535153 ],
       [ 0.45429607]]) <Unit('elementary_charge')>

In [ ]:
test_mol[0].conformer_quantity

array([[-1.25471834,  0.68229875, -0.67971235],
       [-1.85845911, -0.30101415,  0.3355888 ],
       [-0.89300086, -0.41681653,  1.3497422 ],
       [ 0.35976166, -0.44634367,  0.72908314],
       [ 0.23729215,  0.59589564, -0.38179175],
       [ 0.71955659,  1.79205886,  0.01817445],
       [ 0.97078021,  0.24513641, -1.4536694 ],
       [ 1.46639057, -0.18563377,  1.72534578],
       [ 1.63135068, -1.34326994,  2.49459367],
       [-1.59060063,  1.69524064, -0.50401824],
       [-1.45855145,  0.41770197, -1.70844257],
       [-2.77719369,  0.04851399,  0.78206526],
       [-2.03979799, -1.27186493, -0.11840523],
       [ 0.52563888, -1.41250883,  0.25824935],
       [ 1.19503643,  0.66712811,  2.33712881],
       [ 2.37780502,  0.05598759,  1.18389061],
       [ 2.22218569, -1.16612567,  3.21244159]]) <Unit('angstrom')>

In [ ]:
test_off = Molecule.from_mapped_smiles(mapped_smiles=test_mol[0].tagged_smiles, allow_undefined_stereo=True)
test_off.add_conformer(test_mol[0].conformer_quantity.to(unit.bohr))

1

In [ ]:
test_off.assign_partial_charges('am1bcc')
test_off.partial_charges

array([-0.15928235,  0.13051765, -0.42148235,  0.05421765,  0.39171765,
       -0.23168235, -0.23168235,  0.13451765, -0.58968235,  0.08581765,
        0.08581765,  0.05981765,  0.05981765,  0.09081765,  0.06331765,
        0.06331765,  0.41411765]) <Unit('elementary_charge')>