In [1]:
from chargecraft.storage.storage import MoleculePropRecord, MoleculePropStore
from openff.toolkit.topology import Molecule
from openff.units import unit
from openff.recharge.esp import ESPSettings
from openff.recharge.grids import LatticeGridSettings
from openff.recharge.esp.storage import MoleculeESPRecord
from openff.recharge.charges.resp import generate_resp_charge_parameter
from openff.recharge.charges.resp.solvers import IterativeSolver
import numpy as np

resp_solver = IterativeSolver()


def calculate_resp_charges(openff_mol: Molecule,
                           grid: unit.Quantity,
                           esp: unit.Quantity,
                           qc_data_settings: ESPSettings) -> list[float]:
    """Calculate resp charges given a set of input data
    
    Parameters
    ----------
    grid: unit.Quantity
        grid in which the ESP was calculate don
    esp: unit.Quantity
        esp calculated from the qm calculation
    qc_data_settings: ESPSettings
        esp settings the esp was calculated at
        
    Returns
    -------
    list[float]
        list of resp charges
    
    
    """
    qc_data_record = MoleculeESPRecord.from_molecule(
        openff_mol, openff_mol.conformers[0], grid, esp, None, qc_data_settings
    )

    resp_charge_parameter = generate_resp_charge_parameter(
        [qc_data_record], resp_solver
    )
    
    matchs = openff_mol.chemical_environment_matches(query=resp_charge_parameter.smiles)
    resp_charges = [0.0 for _ in range(openff_mol.n_atoms)]
    for match in matchs:
        for i, atom_indx in enumerate(match):
            resp_charges[atom_indx] = resp_charge_parameter.value[i]
    
    return np.round(resp_charges, 4).tolist()

In [2]:
prop_store = MoleculePropStore("/mnt/storage/nobackup/nca121/paper_charge_comparisons/async_chargecraft_more_workers/conformer_test/qc_archive_run/conformers.db", cache_size=1000)


In [3]:
smiles_list = prop_store.list()
smiles_list[0]

'O=[N+]([O-])OCC[NH+](CCO[N+](=O)[O-])CCO[N+](=O)[O-]'

In [4]:
retrieved = prop_store.retrieve(smiles_list[0])

In [5]:
retrieved = prop_store.retrieve(smiles_list[0])[0]
tagged_smiles = retrieved.tagged_smiles
conformer = retrieved.conformer_quantity

openff_mol = Molecule.from_mapped_smiles(tagged_smiles)
openff_mol.add_conformer(conformer)
grid = retrieved.grid_coordinates_quantity#.flatten()
esp = retrieved.esp_quantity.reshape(-1,1)


In [30]:
grid

array([[-6.36396103, -4.59619408,  0.17583647],
       [-6.36396103, -4.59619408,  0.88294325],
       [-6.36396103, -4.24264069, -0.17771692],
       ...,
       [ 7.4246212 , -1.76776695, -0.17771692],
       [ 7.4246212 , -1.76776695,  0.52938986],
       [ 7.4246212 , -1.41421356,  0.17583647]]) <Unit('angstrom')>

In [35]:
esp.reshape(-1,1).shape

(4312, 1)

In [39]:
esp

array([[0.06644078],
       [0.06581643],
       [0.06937767],
       ...,
       [0.06058999],
       [0.06085395],
       [0.06139451]]) <Unit('hartree / elementary_charge')>

In [31]:
openff_mol.conformers[0]


array([[ 0.52450678,  1.38870686,  0.04129899],
       [-0.12353766,  2.60079429,  0.67658654],
       [ 0.80940267,  3.630955  ,  0.39610314],
       [ 0.37596596,  4.91662203,  0.85787727],
       [ 1.16403767,  5.76121342,  0.61846705],
       [-0.68800644,  4.94251346,  1.40260631],
       [-0.13253811,  0.09703388,  0.45394847],
       [ 0.50642316, -1.07780767, -0.24600767],
       [ 2.00321524, -1.11170331, -0.02281052],
       [ 2.35732982, -2.41248222, -0.46099166],
       [ 3.76959756, -2.65649039, -0.40626174],
       [ 4.04393783, -3.74384232, -0.77295292],
       [ 4.43945937, -1.75057104, -0.00717361],
       [-1.62603984,  0.15867358,  0.23623056],
       [-2.35093113, -1.12414614,  0.56851581],
       [-2.21496609, -1.96630172, -0.57009944],
       [-3.01466319, -3.16247635, -0.49774046],
       [-2.90894448, -3.81643592, -1.47438685],
       [-3.63826692, -3.31517789,  0.50658514],
       [ 1.5640137 ,  1.34351036,  0.35036036],
       [ 0.47774638,  1.4357969 , -1.04270882],
       [-1.09137758,  2.8345867 ,  0.23895778],
       [-0.23868218,  2.47595255,  1.75455494],
       [ 0.0262407 , -0.01969306,  1.45554296],
       [ 0.05467978, -1.97745434,  0.15370745],
       [ 0.25651492, -0.99523765, -1.29782365],
       [ 2.52882796, -0.35755666, -0.60382538],
       [ 2.25185944, -0.98535893,  1.03282832],
       [-1.77804124,  0.43747796, -0.80264724],
       [-2.00563639,  0.9488186 ,  0.87517109],
       [-1.94381959, -1.60017842,  1.46241003],
       [-3.39830808, -0.89974154,  0.75044484]]) <Unit('angstrom')>

In [40]:
retrieved.esp_settings

ESPSettings(basis='def2-tzvpp', method='wb97x-d', grid_settings=LatticeGridSettings(type='fcc', spacing=0.5, inner_vdw_scale=1.4, outer_vdw_scale=2.0), pcm_settings=None, psi4_dft_grid_settings=<DFTGridSettings.Default: 'default'>, ddx_settings=None)

In [48]:
esp_settings = ESPSettings(grid_settings=LatticeGridSettings(type='fcc', spacing=0.5, inner_vdw_scale=1.4, outer_vdw_scale=2.0))


calculate_resp_charges(
    openff_mol=openff_mol,
    grid= retrieved.grid_coordinates,
    esp= retrieved.esp.reshape(-1,1),
    qc_data_settings= retrieved.esp_settings
)

[-0.29,
 0.1213,
 -0.3505,
 0.8191,
 -0.2951,
 -0.3605,
 -0.1936,
 -0.29,
 0.1213,
 -0.3505,
 0.8191,
 -0.2951,
 -0.3605,
 -0.29,
 0.1213,
 -0.3505,
 0.8191,
 -0.2951,
 -0.3605,
 0.221,
 0.221,
 0.0932,
 0.0932,
 0.3761,
 0.221,
 0.221,
 0.0932,
 0.0932,
 0.221,
 0.221,
 0.0932,
 0.0932]